# Generated by Django 6.0.5 on 2026-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=8)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('type_service', models.CharField(choices=[('eau', 'ماء'), ('electricite', 'كهرباء')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'قيد الانتظار'), ('en_cours', 'قيد المعالجة'), ('acceptee', 'مقبولة'), ('refusee', 'مرفوضة')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
