# Generated by Django 6.0.5 on 2026-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='certificat_propriete',
            field=models.FileField(blank=True, null=True, upload_to='documents/certificats/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='copie_cin',
            field=models.FileField(blank=True, null=True, upload_to='documents/cin/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='plan_situation',
            field=models.FileField(blank=True, null=True, upload_to='documents/plans/'),
        ),
    ]
