# Generated by Django 6.0.2 on 2026-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_demande_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='certificat_exonération',
            field=models.FileField(blank=True, null=True, upload_to='documents/certificats/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='plan_architacturel',
            field=models.FileField(blank=True, null=True, upload_to='documents/plans/'),
        ),
    ]
