# Generated by Django 6.0.2 on 2026-05-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_demande_certificat_exonération_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='certificat_exonération',
            new_name='certificat_exoneration',
        ),
    ]
