# Generated by Django 6.0.2 on 2026-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_certificat_exonération_demande_certificat_exoneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='recu',
            field=models.FileField(blank=True, null=True, upload_to='recus/'),
        ),
    ]
